export const GET_CATEGORY="GET_CATEGORY";
export const GET_ALLPRODUCT="GET_ALLPRODUCT";
export const GET_CATEGORY_PRODUCT="GET_CATEGORY_PRODUCT";
export const ADD_TOD_CARD="ADD_TOD_CARD";
export const DELETE_TO_CARD="DELETE_TO_CARD";